# AnnNet showcase

A guided tour of the public API. Ten sections, each self-contained, taking you from
the simplest binary graph to the multilayer math API.

This notebook is shipped with empty outputs — run all cells to populate.

**Sections**

1. Hello AnnNet
2. Attributes everywhere
3. Slices for conditions
4. Hyperedges for reactions
5. Multilayer for time / condition
6. Multilayer math
7. Views & subgraphs
8. IO buffet (round-trip via several formats)
9. Backend interop
10. History & replay

In [1]:
import annnet

print(annnet.__version__ if hasattr(annnet, '__version__') else 'dev')

0.3.0

## 1. Hello AnnNet

The simplest entry point. Construct a directed graph, add a few nodes and edges, look at the shape.

In [2]:
from annnet import AnnNet

G = AnnNet(directed=True)
G.add_nodes(['A', 'B', 'C', 'D'])
G.add_edges('A', 'B', edge_id='e1', weight=1.0)
G.add_edges('B', 'C', edge_id='e2', weight=2.0)
G.add_edges('C', 'D', edge_id='e3', weight=1.5)
G

AnnNet object with n_nodes × n_edges = 4 × 3
    directed: True
    slices: ['default']

In [3]:
# Shape
print('nv, ne =', len(G.N), len(G.E))
print('shape =', G.shape)
print('directed =', G.summary()['directed'])

nv, ne = 4 3
shape = (4, 3)
directed = True

In [4]:
# The variadic add_nodes forms
G2 = AnnNet(directed=False)
G2.add_nodes('single')  # singleton string
G2.add_nodes(['a', 'b', 'c'])  # list of ids
G2.add_nodes([{'node_id': 'd', 'color': 'red'}])  # dict with attrs
G2.add_nodes([('e', {'color': 'blue'})])  # (id, attrs) tuple
print(sorted(list(G2.N)))

['a', 'b', 'c', 'd', 'e', 'single']

In [5]:
# Iterate edges
for eid in list(G.E):
    rec = G.E.at(eid)
    print(f'  {eid}: {set(rec.source)} -> {set(rec.target)}  weight={rec.weight}')

  e1: {'A'} -> {'B'}  weight=1.0
  e2: {'B'} -> {'C'}  weight=2.0
  e3: {'C'} -> {'D'}  weight=1.5

## 2. Attributes everywhere

Node, edge, slice, and graph-level attributes live in narwhals-backed tables.
Bulk variants exist for every setter.

In [6]:
# Node attributes
G.attrs.update('nodes', {'A': {'label': 'alpha', 'tier': 1}})
G.attrs.update('nodes', {
        'B': {'label': 'beta', 'tier': 1},
        'C': {'label': 'gamma', 'tier': 2},
        'D': {'label': 'delta', 'tier': 2},
    })

# Single-attr read
print('A.label =', G.attrs.row('nodes', 'A').get('label'))
print('B full =', dict(G.attrs.row('nodes', 'B')))

A.label = alpha
B full = {'label': 'beta', 'tier': 1}

In [7]:
# Edge attributes (bulk). 'kind' / 'weight' / 'directed' are reserved
# (structural columns), so use a different key.
G.attrs.update('edges', {
        'e1': {'confidence': 0.9, 'interaction': 'activation'},
        'e2': {'confidence': 0.7, 'interaction': 'inhibition'},
        'e3': {'confidence': 0.95, 'interaction': 'activation'},
    })

# Filter by attribute
activations = list(G.E.select(interaction='activation').ids)
print('activation edges:', activations)

activation edges: ['e1', 'e3']

In [8]:
# Graph-level metadata (uns-style)
G.uns['study'] = 'showcase'
G.uns['author'] = 'demo'
print(dict(G.uns))

{'study': 'showcase', 'author': 'demo'}

In [9]:
# Reserved keys are rejected — they're part of the structural contract
try:
    G.attrs.update('edges', {'e1': {'source': 'X'}})
except ValueError as e:
    print('caught:', e)

caught: edges attributes use reserved key(s): ['source']. These names are part of the structural / dispatch contract; rename your attribute(s) to use a different key.

## 3. Slices for conditions

Slices are condition / cohort / sample subsets — like obs categories in AnnData, but for nodes and edges together.

In [10]:
G.slices.add('control', cohort='wt')
G.slices.add('treated', cohort='ko')
print(G.slices.list())

['default', 'control', 'treated']

In [11]:
# Add edges directly into a slice
G.add_edges('A', 'D', edge_id='e_extra', slice='treated', weight=3.0)
print('treated edges:', G.slices.edges('treated'))
print('treated nodes:', G.slices.nodes('treated'))

treated edges: {'e_extra'}
treated nodes: {'A', 'D'}

In [12]:
# Slice algebra
G.slices.add_edges('control', ['e1', 'e2'])
G.slices.add_edges('treated', ['e2', 'e3', 'e_extra'])

both = G.slices.intersect(['control', 'treated'])
print('intersection (edges):', both['edges'])
union = G.slices.union(['control', 'treated'])
print('union (edges):', sorted(union['edges']))

intersection (edges): {'e2'}
union (edges): ['e1', 'e2', 'e3', 'e_extra']

In [13]:
# Per-slice weight overrides — useful for condition-specific weights
G.attrs.update('edge_slices', {('treated', 'e2'): {'weight': 99.0}})
print('global e2 weight:', G.E.effective_weight('e2'))
print('treated e2 weight:', G.E.effective_weight('e2', slice='treated'))

global e2 weight: 2.0
treated e2 weight: 99.0

## 4. Hyperedges for reactions

A hyperedge connects an arbitrary set of nodes. Two flavours:

- **Undirected** — pass a list of members.
- **Directed** — pass `src=[heads]`, `tgt=[tails]`.

In [14]:
H = AnnNet(directed=False)
H.add_nodes(['Glc', 'ATP', 'G6P', 'ADP'])

# Undirected: a complex of three species
H.add_edges(['Glc', 'ATP', 'G6P'], edge_id='complex_A')

# Directed reaction: hexokinase  Glc + ATP -> G6P + ADP
H.add_edges(src=['Glc', 'ATP'], tgt=['G6P', 'ADP'], edge_id='hexokinase')
print('ne =', len(H.E))
for eid in list(H.E):
    rec = H.E.at(eid)
    print(
        f'  {eid}: src={set(rec.source) if rec.source else None}, '
        f'tgt={set(rec.target) if rec.target else None}'
    )

ne = 2
  complex_A: src={'ATP', 'G6P', 'Glc'}, tgt={'ATP', 'G6P', 'Glc'}
  hexokinase: src={'ATP', 'Glc'}, tgt={'ADP', 'G6P'}

In [15]:
# Pretty edge view shows hyperedges with members / head / tail columns
H.attrs.table('edges', derived=True).head(5)

shape: (2, 13)
┌────────────┬───────┬──────────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ edge_id    ┆ kind  ┆ directed ┆ weight ┆ … ┆ head        ┆ tail        ┆ members    ┆ effective_ │
│ ---        ┆ ---   ┆ ---      ┆ ---    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ weight     │
│ str        ┆ str   ┆ bool     ┆ f64    ┆   ┆ list[str]   ┆ list[str]   ┆ list[str]  ┆ ---        │
│            ┆       ┆          ┆        ┆   ┆             ┆             ┆            ┆ f64        │
╞════════════╪═══════╪══════════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ complex_A  ┆ hyper ┆ false    ┆ 1.0    ┆ … ┆ null        ┆ null        ┆ ["ATP",    ┆ 1.0        │
│            ┆       ┆          ┆        ┆   ┆             ┆             ┆ "G6P",     ┆            │
│            ┆       ┆          ┆        ┆   ┆             ┆             ┆ "Glc"]     ┆            │
│ hexokinase ┆ hyper ┆ true     ┆ 1.0    ┆ … ┆ ["ATP",     ┆ ["ADP",     ┆ null       ┆ 1.0        │
│            ┆       ┆          ┆        ┆   ┆ "Glc"]      ┆ "G6P"]      ┆            ┆            │
└────────────┴───────┴──────────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [16]:
# Stoichiometry: read the signed incidence column, through the public API
import numpy as np

S = H.S
col = H.idx.edge_to_col('hexokinase')
print('hexokinase column:')
for vid in list(H.N):
    val = S[H.idx.entity_to_row(vid), col]
    print(f'  {vid:>6}: {val:+.2f}')

hexokinase column:
     Glc: +1.00
     ATP: +1.00
     G6P: -1.00
     ADP: -1.00

## 5. Multilayer for time / condition

Aspects partition nodes into layers. A node like `A` can live in multiple layers; the
*supra-node* `(A, ('t1',))` is the actual indexed entity. Intra / inter / coupling edges
have explicit roles.

In [17]:
import warnings

M = AnnNet(directed=False)
with warnings.catch_warnings():
    warnings.simplefilter('ignore')
    # One aspect 't' with two elementary layers.
    M.layers.set_aspects(['t'], {'t': ['t1', 't2']})

    # Same nodes A and B in both layers.
    M.add_nodes(['A', 'B'], layer={'t': 't1'})
    M.add_nodes(['A', 'B'], layer={'t': 't2'})

    # Intra-layer edges.
    M.add_edges(('A', ('t1',)), ('B', ('t1',)), edge_id='e_t1', weight=1.0)
    M.add_edges(('A', ('t2',)), ('B', ('t2',)), edge_id='e_t2', weight=1.0)

print('aspects:', M.layers.list_aspects())
print('layers:', M.layers.list_layers())

aspects: ('t',)
layers: {'t': ['t1', 't2']}

In [18]:
# Add diagonal couplings (A in t1 <-> A in t2, B in t1 <-> B in t2)
with warnings.catch_warnings():
    warnings.simplefilter('ignore')
    n_added = M.layers.add_layer_coupling_pairs([(('t1',), ('t2',))])
print('coupling edges added:', n_added)

coupling edges added: 2

In [19]:
# Subgraph for a specific layer
sub_t1 = M.layers.subgraph_from_layer_tuple(('t1',))
print('t1 subgraph: nv=', len(sub_t1.N), 'ne=', len(sub_t1.E))

t1 subgraph: nv= 2 ne= 1

## 6. Multilayer math

Supra-adjacency, supra-Laplacian, transition matrix, layer descriptors.
Same `M` graph from section 5.

In [20]:
A = M.layers.supra_adjacency()
print('supra-adjacency (', A.shape, '):')
print(A.toarray())

supra-adjacency ( (4, 4) ):
[[0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]]

In [21]:
# Decomposition: A = A_intra + A_inter + A_coup
A_intra = M.layers.build_intra_block().toarray()
A_inter = M.layers.build_inter_block().toarray()
A_coup = M.layers.build_coupling_block().toarray()
print('intra + inter + coupling == A?', np.allclose(A_intra + A_inter + A_coup, A.toarray()))

intra + inter + coupling == A? True

In [22]:
# Combinatorial Laplacian
L = M.layers.supra_laplacian(kind='comb').toarray()
print('L = D - A:')
print(L)
print('L symmetric?', np.allclose(L, L.T))

L = D - A:
[[ 2. -1. -1.  0.]
 [-1.  2.  0. -1.]
 [-1.  0.  2. -1.]
 [ 0. -1. -1.  2.]]
L symmetric? True

In [23]:
# Random walk transition matrix is row-stochastic
P = M.layers.transition_matrix().toarray()
print('row sums of P:', P.sum(axis=1))

row sums of P: [1. 1. 1. 1.]

In [24]:
# Spectral probes
lam2, fiedler = M.layers.algebraic_connectivity()
print('algebraic connectivity (lambda_2):', lam2)
print('Fiedler vector:', fiedler)

algebraic connectivity (lambda_2): 2.0
Fiedler vector: [ 0.53136699  0.4665288  -0.4665288  -0.53136699]

In [25]:
# Layer-aware descriptors
pc = M.layers.participation_coefficient()
vers = M.layers.versatility()
print('participation coefficient:', pc)
print('versatility:', vers)

participation coefficient: {'A': 0.5, 'B': 0.5}
versatility: {'A': 1.0, 'B': 1.0}

## 7. Views & subgraphs

`G.views.*` returns lazy, filterable dataframes. The `materialize()` path on a `GraphView`
gives you a concrete subgraph.

In [26]:
# Edge table view
G.attrs.table('edges', derived=True).head(5)

shape: (4, 15)
┌─────────┬────────┬──────────┬────────┬───┬─────────┬────────────┬─────────────┬──────────────────┐
│ edge_id ┆ kind   ┆ directed ┆ weight ┆ … ┆ members ┆ confidence ┆ interaction ┆ effective_weight │
│ ---     ┆ ---    ┆ ---      ┆ ---    ┆   ┆ ---     ┆ ---        ┆ ---         ┆ ---              │
│ str     ┆ str    ┆ bool     ┆ f64    ┆   ┆ null    ┆ f64        ┆ str         ┆ f64              │
╞═════════╪════════╪══════════╪════════╪═══╪═════════╪════════════╪═════════════╪══════════════════╡
│ e1      ┆ binary ┆ true     ┆ 1.0    ┆ … ┆ null    ┆ 0.9        ┆ activation  ┆ 1.0              │
│ e2      ┆ binary ┆ true     ┆ 2.0    ┆ … ┆ null    ┆ 0.7        ┆ inhibition  ┆ 2.0              │
│ e3      ┆ binary ┆ true     ┆ 1.5    ┆ … ┆ null    ┆ 0.95       ┆ activation  ┆ 1.5              │
│ e_extra ┆ binary ┆ true     ┆ 3.0    ┆ … ┆ null    ┆ null       ┆ null        ┆ 3.0              │
└─────────┴────────┴──────────┴────────┴───┴─────────┴────────────┴─────────────┴──────────────────┘

In [27]:
# Node table view
G.attrs.table('nodes', derived=True).head(5)

shape: (4, 3)
┌─────────┬───────┬──────┐
│ node_id ┆ label ┆ tier │
│ ---     ┆ ---   ┆ ---  │
│ str     ┆ str   ┆ i64  │
╞═════════╪═══════╪══════╡
│ A       ┆ alpha ┆ 1    │
│ B       ┆ beta  ┆ 1    │
│ C       ┆ gamma ┆ 2    │
│ D       ┆ delta ┆ 2    │
└─────────┴───────┴──────┘

In [28]:
# Slice table view
G.attrs.table('slices', derived=True)

shape: (3, 4)
┌──────────┬─────────┬─────────┬────────┐
│ slice_id ┆ n_nodes ┆ n_edges ┆ cohort │
│ ---      ┆ ---     ┆ ---     ┆ ---    │
│ str      ┆ i64     ┆ i64     ┆ str    │
╞══════════╪═════════╪═════════╪════════╡
│ default  ┆ 4       ┆ 3       ┆ null   │
│ control  ┆ 3       ┆ 2       ┆ wt     │
│ treated  ┆ 4       ┆ 3       ┆ ko     │
└──────────┴─────────┴─────────┴────────┘

In [29]:
# Materialize a filtered subgraph
v = G.view(nodes=['A', 'B', 'C'], edges=['e1', 'e2'])
sub = v.materialize()
print('subgraph nv, ne =', len(sub.N), len(sub.E))
print('subgraph nodes:', sorted(list(sub.N)))

subgraph nv, ne = 3 2
subgraph nodes: ['A', 'B', 'C']

## 8. IO buffet

Round-trip the graph through several formats. Each branch is independent; cherry-pick
what you need.

In [30]:
import tempfile
from pathlib import Path

tmp = Path(tempfile.mkdtemp(prefix='annnet_showcase_'))
print('using temp dir:', tmp)

using temp dir: <temporary directory>

In [31]:
# Parquet (lossless)
from annnet import to_parquet, from_parquet

to_parquet(G, tmp / 'graph_parquet')
G_back = from_parquet(tmp / 'graph_parquet')
print('parquet round-trip: nv=', len(G_back.N), 'ne=', len(G_back.E))

parquet round-trip: nv= 4 ne= 4

In [32]:
# JSON
from annnet import to_json, from_json

to_json(G, tmp / 'graph.json')
G_json = from_json(tmp / 'graph.json')
print('json round-trip: nv=', len(G_json.N), 'ne=', len(G_json.E))

json round-trip: nv= 4 ne= 4

In [33]:
# Native .annnet format (compressed, manifest-aware)
from annnet import read, write

write(G, tmp / 'graph.annnet')
G_native = read(tmp / 'graph.annnet')
print('.annnet round-trip: nv=', len(G_native.N), 'ne=', len(G_native.E))

.annnet round-trip: nv= 4 ne= 4

In [34]:
# CX2 (Cytoscape Exchange) — useful for visualization
from annnet import to_cx2, from_cx2

cx2 = to_cx2(G)
G_cx2 = from_cx2(cx2)
print('cx2 round-trip: nv=', len(G_cx2.N), 'ne=', len(G_cx2.E))

cx2 round-trip: nv= 4 ne= 4

In [35]:
# DataFrames (per-table)
from annnet import to_dataframes

dfs = to_dataframes(G)
print('tables exported:', list(dfs.keys()))

tables exported: ['nodes', 'edges', 'hyperedges', 'slices', 'slice_weights']

## 9. Backend interop

Three backends: NetworkX (`G.nx`), igraph (`G.ig`), graph-tool (`G.gt`, optional).
Each is exposed as an accessor that forwards a familiar API onto a snapshot of the graph.

In [36]:
# NetworkX accessor: get the underlying nx graph via .backend()
import networkx as nx

nxG = G.nx.backend()
print('nx graph type:', type(nxG).__name__)
print('degree(A):', nxG.degree('A'))
print('shortest_path A->D:', nx.shortest_path(nxG, 'A', 'D'))

nx graph type: MultiDiGraph
degree(A): 2
shortest_path A->D: ['A', 'D']

annnet/core/backend_accessors/_base.py:166: RuntimeWarning: AnnNet-NX conversion is lossy: multiple slices flattened into single NX graph.
  entry = dict(build())

In [37]:
# Peek at node IDs the accessor sees
print('peek nodes:', G.nx.peek_nodes(10))

peek nodes: ['A', 'B', 'C', 'D']

In [38]:
# igraph accessor (same shape)
igG_view = G.ig.backend()
print('ig graph type:', type(igG_view).__name__)
print('vcount:', igG_view.vcount(), 'ecount:', igG_view.ecount())

ig graph type: Graph
vcount: 4 ecount: 4

annnet/core/backend_accessors/_base.py:166: RuntimeWarning: AnnNet-igraph conversion is lossy: multiple slices flattened into single igraph graph.
  entry = dict(build())

In [39]:
# Export to igraph + manifest, then re-import losslessly
from annnet import to_igraph, from_igraph

ig_graph, manifest = to_igraph(G)
G_via_ig = from_igraph(ig_graph, manifest)
print('igraph round-trip: nv=', len(G_via_ig.N), 'ne=', len(G_via_ig.E))

igraph round-trip: nv= 4 ne= 4

## 10. History & replay

`G.history` records every mutating call. Useful for provenance and for replaying the
construction pipeline on a fresh graph.

In [40]:
# Inspect the call log — G.history() is callable and returns a list of events
log = G.history()
print('total mutating calls:', len(log))
for entry in log[:5]:
    print(
        ' ',
        entry.get('op'),
        '-',
        {k: v for k, v in entry.items() if k in ('args', 'kwargs', 'result')},
    )

total mutating calls: 5
  add_nodes - {'result': ['A', 'B', 'C', 'D']}
  add_edges - {'args': ['A', 'B'], 'kwargs': {'edge_id': 'e1', 'weight': 1.0}, 'result': 'e1'}
  add_edges - {'args': ['B', 'C'], 'kwargs': {'edge_id': 'e2', 'weight': 2.0}, 'result': 'e2'}
  add_edges - {'args': ['C', 'D'], 'kwargs': {'edge_id': 'e3', 'weight': 1.5}, 'result': 'e3'}
  add_edges - {'args': ['A', 'D'], 'kwargs': {'edge_id': 'e_extra', 'slice': 'treated', 'weight': 3.0}, 'result': 'e_extra'}

In [41]:
# Tag named snapshots for later diffing
G.history.snapshot('after_construction')
G.attrs.update('nodes', {'A': {'extra': 'just-added'}})
G.add_nodes(['E'])
G.history.snapshot('after_extra')

# Each snapshot captures node / edge / slice id sets
for snap in G.history.list_snapshots():
    print(snap['label'], '— version:', snap['version'], 'nv:', len(snap['node_ids']))

after_construction — version: 5 nv: 4
after_extra — version: 7 nv: 5

In [42]:
# Diff two snapshots: what changed between marks?
diff = G.history.diff('after_construction', 'after_extra')
print(diff.summary())

Diff: after_construction - after_extra

Nodes: +1 added, 0 removed
Edges: +0 added, 0 removed
slices: +0 added, 0 removed

---

That's the tour. Next stops:

- `notebooks/special/sp01_directed_hyperedges.ipynb` — hyperedge stoichiometry deep-dive
- `notebooks/special/sp02_multilayer_math.ipynb` — supra-Laplacian / random walks / modularity
- `notebooks/special/sp03_flexible_edge_orientation.ipynb` — edge direction policies
- `notebooks/use_cases/uc1..uc3` — real-data workflows
- `notebooks/benchmark.ipynb` — tunable speed/memory profiling